// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grqvrhaaauzbbpetkqdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdycXZyaGFhYXV6YmJwZXRrcWRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMTQyOTksImV4cCI6MjA3Mzg5MDI5OX0.pPgUrNEwXqXcVCoR9BoLPDF3blrWR7HLEGLJsHqZuAI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});